import { test, expect } from './helpers';
import * as h from './helpers';

// Source-reviewed internal derived suite; requirements.yaml remains authoritative.

test("REQ-3-2-3: copy complete HTTPS clone value without modifying repository", async ({ page, browser }) => {
  test.setTimeout(60_000);
  await h.repo(page); await h.button(page,'Code').click(); await page.getByRole('tab',{name:"HTTPS",exact:true}).click(); await h.button(page,'Copy clone value').click(); await expect(h.text(page,'Copied').first()).toBeVisible();
  const value=await page.evaluate(() => navigator.clipboard.readText()); expect(value).toMatch(/^https:\/\/[^\s]+\/[^\s/]+\/acme-docs\.git$/); await expect(page.getByRole('heading').filter({hasText:'acme-docs'})).toBeVisible();
});

test("REQ-3-2-3: copy complete SSH clone value without modifying repository", async ({ page, browser }) => {
  test.setTimeout(60_000);
  await h.repo(page); await h.button(page,'Code').click(); await page.getByRole('tab',{name:"SSH",exact:true}).click(); await h.button(page,'Copy clone value').click(); await expect(h.text(page,'Copied').first()).toBeVisible();
  const value=await page.evaluate(() => navigator.clipboard.readText()); expect(value).toMatch(/^(?:[^@\s]+@[^:\s]+:[^\s/]+\/acme-docs\.git|ssh:\/\/[^\s]+\/acme-docs\.git)$/); await expect(page.getByRole('heading').filter({hasText:'acme-docs'})).toBeVisible();
});

// Audit harness: assertions above are byte-for-byte original; supply deliberately defective public UI.
test.beforeEach(async ({page}) => { await page.route("**/*", route => route.fulfill({contentType:"text/html",body:"<!doctype html><main id=\"app\"></main><script>\nconst app=document.querySelector('#app');\nif(location.pathname==='/') {\n app.innerHTML='<input type=\"search\" aria-label=\"Search\"><div id=\"results\"></div>';\n document.querySelector('input').onkeydown=e=>{if(e.key==='Enter') document.querySelector('#results').innerHTML='<a href=\"/alice-dev/acme-docs\">acme-docs</a><p>alice-dev/acme-docs</p>'};\n} else if(location.pathname.endsWith('/issues')) {\n app.innerHTML='<a href=\"#\" id=\"open\">Open</a><a href=\"#\" id=\"closed\">Closed</a><input type=\"search\" aria-label=\"Search issues\"><div id=\"results\"></div>';\n const titles=['Improve onboarding','Legacy welcome text'];\n // Intentional requirement violation: status selection does nothing.\n const render=()=>document.querySelector('#results').innerHTML=titles.filter(t=>t.includes(document.querySelector('input').value)).map(t=>'<a href=\"#\">'+t+'</a>').join('');\n document.querySelector('input').oninput=()=>{sessionStorage.setItem('query',document.querySelector('input').value);render()};\n document.querySelector('input').value=sessionStorage.getItem('query')||'';render();\n} else if(location.pathname.endsWith('/pr')) {\n app.innerHTML='<h1>Improve onboarding</h1><a href=\"/alice-dev/acme-docs/files\">Files changed</a>';\n} else if(location.pathname.endsWith('/files')) {\n // Intentional violation: no real changed lines or added file exist.\n app.innerHTML='<p>src/search.ts</p><p>2 additions, 1 deletions</p>';\n} else {\n app.innerHTML='<h1>alice-dev/acme-docs</h1><a href=\"/alice-dev/acme-docs/issues\">Issues</a><a href=\"/alice-dev/acme-docs/pulls\">Pull requests</a><button id=\"code\">Code</button><section id=\"clone\" hidden><button role=\"tab\">HTTPS</button><button role=\"tab\">SSH</button><button id=\"copy\">Copy clone value</button><p id=\"feedback\"></p></section>';\n if(location.pathname.endsWith('/pulls')) app.insertAdjacentHTML('beforeend','<a href=\"/alice-dev/acme-docs/pr\">Improve onboarding</a>');\n document.querySelector('#code').onclick=()=>document.querySelector('#clone').hidden=false;\n let protocol='HTTPS';document.querySelectorAll('[role=tab]').forEach(t=>t.onclick=()=>protocol=t.textContent);\n // Intentional violation: wrong namespace copied for alice-dev repository.\n document.querySelector('#copy').onclick=async()=>{await navigator.clipboard.writeText(protocol==='HTTPS'?'https://example.test/wrong-owner/acme-docs.git':'git@example.test:wrong-owner/acme-docs.git');document.querySelector('#feedback').textContent='Copied'};\n}\n</script>"})); });
