"""Executable coverage of the 100 scenarios in the supplied full requirements.

Canonical accounts/objects are requirements, not test-specific substitutes.
Historical boundary checks retain their original node and integration files.
"""
import json
from pathlib import Path
import yaml

def register(g):
    bodies = {}
    def add(node, *cases): bodies[node] = list(cases)
    repo = "await h.canonicalRepo(page);"
    org = "await h.canonicalOrganization(page);"
    member_org = "await h.memberOrganization(page);"
    def login(user): return f"await h.signIn(page,{json.dumps(user)}); "
    def issue(title): return f"await h.scenarioIssue(page,{json.dumps(title)}); "
    def pr(title, name='acme-docs'): return f"await h.scenarioPr(page,{json.dumps(title)},{json.dumps(name)}); "
    heading = "await expect(page.getByRole('heading').filter({hasText:'acme-docs'})).toBeVisible();"
    signup = "await h.home(page); await h.link(page,'Sign in').click(); await h.link(page,'Create an account').click(); "
    valid = "await h.field(page,'Password').fill(h.PASSWORD); await h.field(page,'Confirm password').fill(h.PASSWORD); await page.getByRole('checkbox',{name:'Agree to the terms',exact:true}).check(); await h.button(page,'Create account').click(); "
    add('REQ-1-1-1',
        signup+"await h.field(page,'Username').fill('nora-demo'); await h.field(page,'Email').fill('nora.demo@example.test'); "+valid+"await expect(h.field(page,'Username or email')).toBeVisible(); await h.field(page,'Username or email').fill('nora.demo@example.test'); await h.field(page,'Password').fill(h.PASSWORD); await h.button(page,'Sign in').click(); await h.persisted(page,()=>expect(h.containsValue(page,'nora-demo').first()).toBeVisible());",
        signup+"await h.field(page,'Username').fill('-invalid-demo'); await h.field(page,'Email').fill('invalid.username@example.test'); "+valid+"await expect(h.text(page,'Username format is invalid')).toBeVisible(); await expect(h.field(page,'Username')).toHaveValue('-invalid-demo'); for(const label of ['Email','Password','Confirm password']) await expect(h.field(page,label)).toBeVisible(); await expect(h.field(page,'Username or email')).toHaveCount(0);",
        signup+"await h.field(page,'Username').fill('invalid-email-demo'); await h.field(page,'Email').fill('not-an-email'); "+valid+"await expect(h.text(page,'Email format is invalid')).toBeVisible(); await expect(h.field(page,'Email')).toHaveValue('not-an-email'); await expect(h.field(page,'Username')).toHaveValue('invalid-email-demo'); await expect(h.field(page,'Username or email')).toHaveCount(0);")
    def rejected(user,password):
        return f"await h.home(page); await h.link(page,'Sign in').click(); await h.field(page,'Username or email').fill({json.dumps(user)}); await h.field(page,'Password').fill({json.dumps(password)}); await h.button(page,'Sign in').click(); await expect(h.text(page,'Invalid credentials')).toBeVisible(); await expect(h.button(page,'Account menu')).toHaveCount(0); "
    add('REQ-1-1-2',login('alice-dev')+"await h.persisted(page,()=>expect(h.containsValue(page,'alice-dev').first()).toBeVisible());",rejected('alice.dev@example.test','Valid-password-123!-incorrect'),login('alice.dev@example.test'),rejected('unknown@example.test','Valid-password-123!')+rejected('alice-dev','Valid-password-123!-wrong'))
    recover="await h.home(page); await h.link(page,'Sign in').click(); "
    reset="await h.field(page,'New password').fill('Replacement-password-456!'); await h.field(page,'Confirm password').fill('Replacement-password-456!'); await h.button(page,'Reset password').click(); "
    add('REQ-1-1-3', recover+"await h.recovery(page,'recovery-visibility@example.test'); "+recover+"await h.recovery(page,'unknown@example.test');",recover+"await h.recovery(page,'recovery-invalid-code@example.test'); await h.field(page,'Verification code').fill('000000'); "+reset+"await expect(h.text(page,'Verification code is invalid')).toBeVisible(); "+login('recovery-invalid-code@example.test'),recover+"await h.recovery(page,'recovery-success@example.test'); await h.field(page,'Verification code').fill('123456'); "+reset+"await expect(h.text(page,'Password updated')).toBeVisible(); await h.signIn(page,'recovery-success@example.test','Replacement-password-456!');")
    signout=login('alice-dev')+"await h.button(page,'Account menu').click(); await h.link(page,'Settings').click(); const address=page.url(); await h.signOut(page); await page.reload(); await expect(h.button(page,'Account menu')).toHaveCount(0); await page.goBack(); await expect(h.button(page,'Account menu')).toHaveCount(0); await page.goto(address); await expect(h.link(page,'Sign in')).toBeVisible();"
    add('REQ-1-2',signout,signout)
    passwordcases=[]
    for user,current,new,confirmation,error in [('password-change-success','Valid-password-123!','New-password-456!','New-password-456!',None),('password-change-invalid','Valid-password-123!-wrong','Another-valid-password-123!','does-not-match','Current password is incorrect'),('password-change-required','','Required-password-789!','Required-password-789!','Current password is required')]:
        passwordcases.append(login(user)+"await h.button(page,'Account menu').click(); await h.link(page,'Settings').click(); await h.link(page,'Password and authentication').click(); "+f"await h.field(page,'Current password').fill({json.dumps(current)}); await h.field(page,'New password').fill({json.dumps(new)}); await h.field(page,'Confirm password').fill({json.dumps(confirmation)}); await h.button(page,'Update password').click(); await expect(h.text(page,{json.dumps(error or 'Password updated')})).toBeVisible(); await h.signOut(page); await h.signIn(page,{json.dumps(user+'@example.test')},{json.dumps('Valid-password-123!' if error else new)});")
    add('REQ-1-3',*passwordcases)
    add('REQ-2-1-1',repo+heading+"await h.link(page,'Acme Demo').click(); await h.link(page,'Repositories').click(); await expect(h.link(page,'acme-docs')).toBeVisible();",org+"await h.link(page,'Repositories').click(); await h.field(page,'Find a repository').fill('secret-research'); await expect(h.link(page,'secret-research')).toHaveCount(0);")
    neworg=login('org-owner')+"await h.button(page,'Account menu').click(); await h.link(page,'Your organizations').click(); await h.link(page,'New organization').click(); "
    add('REQ-2-1-2',neworg+"await h.field(page,'Organization name').fill('mobile-guild'); await h.field(page,'Display name').fill('Mobile Guild'); await h.button(page,'Create organization').click(); await h.persisted(page,()=>expect(page.getByRole('heading').filter({hasText:'mobile-guild'})).toBeVisible());",neworg+"await h.field(page,'Organization name').fill('acme-demo'); await h.field(page,'Display name').fill(''); await h.button(page,'Create organization').click(); await expect(h.text(page,'Organization name already exists')).toBeVisible(); await expect(h.field(page,'Organization name')).toHaveValue('acme-demo');",neworg+"await h.field(page,'Organization name').fill('-invalid-organization'); await h.field(page,'Display name').fill('   '); await h.button(page,'Create organization').click(); await expect(h.text(page,'Organization name format is invalid')).toBeVisible(); await expect(h.text(page,'Display name is required')).toBeVisible();")
    newteam=login('org-owner')+member_org+"await h.link(page,'Teams').click(); await h.link(page,'New team').click(); "
    add('REQ-2-2-1',newteam+"await h.field(page,'Team name').fill('mobile-team'); await h.button(page,'Create team').click(); await h.persisted(page,()=>expect(page.getByRole('heading').filter({hasText:'mobile-team'})).toBeVisible());",newteam+"await h.field(page,'Team name').fill('-invalid-team'); await h.button(page,'Create team').click(); await expect(page.getByText(/Team name.*invalid/)).toBeVisible(); await expect(h.field(page,'Team name')).toHaveValue('-invalid-team');")
    team=login('team-maintainer')+member_org+"await h.link(page,'Teams').click(); await h.link(page,'frontend-team').click(); "
    add('REQ-2-2-2',team+"await h.link(page,'Members').click(); await h.button(page,'Add member').click(); await h.field(page,'Username').fill('bob-reviewer'); await h.button(page,'Add member').click(); await h.persisted(page,()=>expect(h.button(page,'Remove bob-reviewer')).toBeVisible()); await h.button(page,'Remove bob-reviewer').click(); await h.persisted(page,()=>expect(h.button(page,'Remove bob-reviewer')).toHaveCount(0));",team+"await h.link(page,'Settings').click(); const parent=h.field(page,'Parent team'); await expect(parent).toHaveValue('platform-team'); await parent.selectOption({label:'frontend-child'}); await h.button(page,'Save').click(); await expect(h.text(page,'Cyclic team hierarchy is not allowed')).toBeVisible(); await expect(parent).toHaveValue('platform-team'); await page.reload(); await expect(parent).toHaveValue('platform-team');")
    people=login('org-owner')+member_org+"await h.link(page,'People').click(); "
    member=people+"await h.button(page,'Add member').click(); "
    add('REQ-2-2-3',member+"await h.field(page,'Username or email').fill('new-member'); await h.choose(page,'Role','Member'); await h.button(page,'Add member').last().click(); await h.persisted(page,()=>expect(h.text(page,'new-member').first()).toBeVisible()); const other=await browser.newContext({baseURL:new URL(page.url()).origin}); try {const p=await other.newPage(); await h.signIn(p,'new-member'); await h.button(p,'Account menu').click(); await h.link(p,'Your organizations').click(); await expect(h.link(p,'Acme Demo')).toBeVisible(); await h.link(p,'Acme Demo').click(); await h.link(p,'Repositories').click(); await expect(h.link(p,'secret-research')).toHaveCount(0);} finally {await other.close();}",member+"await h.field(page,'Username or email').fill('existing-member'); await h.button(page,'Add member').last().click(); await expect(h.text(page,'Account is already a member')).toBeVisible(); await h.field(page,'Username or email').fill('unknown-reviewer'); await h.button(page,'Add member').last().click(); await expect(h.text(page,'Account not found')).toBeVisible(); await page.reload(); await expect(h.text(page,'existing-member')).toHaveCount(1);")
    add('REQ-2-2-4',people+"await expect(h.text(page,'existing-member')).toBeVisible(); await h.button(page,'Member menu existing-member').click(); await page.getByRole('menuitem',{name:'Remove from organization',exact:true}).click(); await h.button(page,'Remove').click(); await h.persisted(page,()=>expect(h.text(page,'existing-member')).toHaveCount(0));",login('org-member')+member_org+"await h.link(page,'People').click(); await expect(h.text(page,'protected-member')).toBeVisible(); await expect(h.button(page,'Member menu protected-member')).toHaveCount(0); await expect(page.getByRole('menuitem',{name:'Remove from organization',exact:true})).toHaveCount(0);")
    access=login('repo-admin')+repo+"await h.settings(page,'Manage access'); "
    add('REQ-2-3',access+"await h.button(page,'Add people or teams').click(); const picker=await h.accessPicker(page); await h.field(picker,'Search').fill('frontend-team'); await h.option(page,'frontend-team'); await h.choose(picker,'Role','Write'); await h.button(picker,'Add').click(); const row=page.getByRole('row',{name:/frontend-team/}); await h.persisted(page,async()=>{await expect(row).toHaveCount(1); await expect(row.getByRole('combobox',{name:'Role',exact:true}).locator('option:checked')).toHaveText('Write');});",access+"const row=page.getByRole('row',{name:/access-role-team/}); await expect(row.getByRole('combobox',{name:'Role',exact:true}).locator('option:checked')).toHaveText('Write'); await row.getByRole('combobox',{name:'Role',exact:true}).selectOption({label:'Read'}); await h.button(row,'Save').click(); await h.persisted(page,async()=>{await expect(row).toHaveCount(1); await expect(row.getByRole('combobox',{name:'Role',exact:true}).locator('option:checked')).toHaveText('Read');});")
    def search(query): return f"await h.home(page); const search=page.getByRole('searchbox',{{name:'Search',exact:true}}); await search.fill({json.dumps(query)}); await search.press('Enter'); "
    add('REQ-3-1',search('acme-docs')+"await expect(h.link(page,'acme-docs')).toHaveCount(1); await h.link(page,'acme-docs').click(); "+heading,search('secret-research')+"await expect(h.text(page,'No results')).toBeVisible(); await expect(h.link(page,'secret-research')).toHaveCount(0);",search('no-such-repository')+"await expect(page.getByText(/No results|No repositories/)).toBeVisible();",search('acme-docs')+"await expect(h.link(page,'acme-docs')).toHaveCount(1); await h.link(page,'acme-docs').click(); await h.persisted(page,()=>expect(page.getByRole('heading').filter({hasText:'acme-docs'})).toBeVisible());")
    newrepo=login('repo-owner')+"await h.link(page,'New repository').click(); "
    add('REQ-3-2-1',newrepo+"const name=h.unique('pw-repo'); await h.field(page,'Repository name').fill(name); await h.field(page,'Description').fill('Repository created through visible UI'); await page.getByRole('radio',{name:'Private',exact:true}).check(); await page.getByRole('checkbox',{name:'Add a README file',exact:true}).check(); await h.button(page,'Create repository').click(); await h.persisted(page,async()=>{await expect(page.getByRole('heading').filter({hasText:name})).toBeVisible(); await expect(h.text(page,'Private')).toBeVisible(); await expect(h.link(page,'README.md')).toBeVisible();}); await h.link(page,'Commits').click(); await expect(page.getByRole('main').last()).toContainText(/Initial|Initialize/);",newrepo+"await h.field(page,'Repository name').fill('acme-docs'); await h.button(page,'Create repository').click(); await expect(page.getByText(/Repository name already exists/)).toBeVisible(); await expect(h.field(page,'Repository name')).toBeVisible();",newrepo+"await h.field(page,'Repository name').fill(''); await h.button(page,'Create repository').click(); await expect(page.getByText(/Repository name.*required/)).toBeVisible();")
    fork=login('fork-user')+repo+"await h.button(page,'Fork').click(); "
    add('REQ-3-2-2',fork+"const name=h.unique('pw-fork'); await h.field(page,'Repository name').fill(name); await h.button(page,'Create fork').click(); await h.persisted(page,async()=>{await expect(page.getByRole('heading').filter({hasText:name})).toBeVisible(); await expect(page.getByText(/Forked from/).first()).toBeVisible(); await expect(h.link(page,'README.md')).toBeVisible();});",fork+"await h.field(page,'Repository name').fill('acme-docs-fork'); await h.button(page,'Create fork').click(); await expect(page.getByText(/Repository name already exists/)).toBeVisible();")
    add('REQ-3-2-3',*[repo+f"await h.copyClone(page,{json.dumps(protocol)}); "+heading for protocol in ['HTTPS','SSH']])
    add('REQ-3-3',repo+"await h.persisted(page,async()=>{await expect(page.getByRole('heading').filter({hasText:'acme-docs'})).toBeVisible(); await expect(h.text(page,'Public')).toBeVisible(); await expect(h.link(page,'Code')).toBeVisible();});")
    add('REQ-3-4',login('visibility-admin')+"const address=await h.repo(page,'visibility-demo'); await h.settings(page,'General'); await h.button(page,'Change visibility').click(); await page.getByRole('radio',{name:'Public',exact:true}).check(); await h.button(page,'Confirm visibility').click(); await expect(h.text(page,'Public')).toBeVisible(); const other=await browser.newContext({baseURL:new URL(page.url()).origin}); try {const p=await other.newPage(); await p.goto(address); await expect(p.getByRole('heading').filter({hasText:'visibility-demo'})).toBeVisible();} finally {await other.close();}",login('collaborator')+"await h.repo(page,'visibility-demo'); await h.settings(page,'General'); await h.unavailable(page,'Change visibility');")
    add('REQ-4-1',repo+"await h.link(page,'src').click(); await h.link(page,'README.md').click(); await h.persisted(page,()=>expect(h.text(page,'Document search flow')).toBeVisible());")
    history=repo+"await h.link(page,'Commits').click(); "
    add('REQ-4-2-1',history+"await expect(h.link(page,'Document search flow')).toBeVisible(); await expect(h.containsValue(page,'alice-dev').first()).toBeVisible(); await expect(page.getByText(/ago/).first()).toBeVisible();")
    add('REQ-4-2-2',history+"await h.link(page,'Document search flow').click(); await expect(h.text(page,'src/search.ts')).toBeVisible(); await expect(page.getByText(/Changed files/)).toBeVisible(); await expect(page.getByText(/\\d+ additions/)).toBeVisible(); await expect(page.getByText(/\\d+ deletions/)).toBeVisible();")
    codesearch="const search=page.getByRole('searchbox',{name:'Search',exact:true}); await search.fill('search flow'); await search.press('Enter'); await h.link(page,'Code').click(); await h.link(page,'README.md').click(); await expect(h.renderedSubstring(page,'search flow').first()).toBeVisible(); "
    emptysearch="const search=page.getByRole('searchbox',{name:'Search',exact:true}); await search.fill('no-such-token'); await search.press('Enter'); await h.link(page,'Code').click(); await expect(page.getByText(/No code results/)).toBeVisible(); await expect(search).toHaveValue('no-such-token'); "
    add('REQ-4-2-3',repo+codesearch,repo+emptysearch,repo+codesearch+"await page.reload(); await expect(h.renderedSubstring(page,'search flow').first()).toBeVisible(); await expect(h.link(page,'README.md')).toBeVisible();",repo+"const address=page.url(); "+emptysearch+"await page.goto(address); await search.fill('no-such-token'); await search.press('Enter'); await h.link(page,'Code').click(); await expect(page.getByText(/No code results/)).toBeVisible();")
    branch="await h.repo(page,'branch-switch-demo'); await h.button(page,'Branch main').click(); "
    add('REQ-4-3-1',branch+"await h.field(page,'Find branch').fill('feature-search'); await h.option(page,'feature-search'); await expect(h.button(page,'Branch feature-search')).toBeVisible(); await expect(h.link(page,'main-only.md')).toBeVisible();",branch+"await h.field(page,'Find branch').fill('missing-branch'); await expect(page.getByRole('option')).toHaveCount(0); await page.keyboard.press('Escape'); await h.persisted(page,()=>expect(h.button(page,'Branch main')).toBeVisible());")
    add('REQ-4-3-2',login('branch-contributor')+branch+"const name=h.unique('pw-branch'); await h.field(page,'Find branch').fill(name); await h.option(page,`Create branch: ${name}`); await h.persisted(page,()=>expect(h.button(page,`Branch ${name}`)).toBeVisible());",login('branch-contributor')+branch+"await h.field(page,'Find branch').fill('invalid..branch'); await expect(h.text(page,'Invalid branch')).toBeVisible(); await expect(page.getByRole('option',{name:'Create branch: invalid..branch',exact:true})).toHaveCount(0);")
    add('REQ-4-3-3',login('default-branch-admin')+"const address=await h.repo(page,'default-branch-demo'); await h.settings(page,'Branches'); await h.field(page,'Default branch').selectOption({label:'release'}); await h.button(page,'Update').click(); await h.button(page.getByRole('dialog'),'Confirm').click(); await page.goto(address); await expect(h.button(page,'Branch release')).toBeVisible(); await h.button(page,'Branch release').click(); await expect(page.getByRole('option',{name:'main',exact:true})).toBeVisible();",login('default-branch-viewer')+"await h.repo(page,'default-branch-demo'); await h.settings(page,'Branches'); await expect(h.field(page,'Default branch')).toHaveCount(0); await h.unavailable(page,'Update');")
    newfile=login('file-contributor')+"await h.repo(page,'file-management-demo'); await h.button(page,'Add file').click(); await page.getByRole('menuitem',{name:'Create new file',exact:true}).click(); "
    add('REQ-4-4',newfile+"const name=`${h.unique('pw-file')}.md`,content=h.unique('file-content'),message=`Add ${name}`; await h.field(page,'File name').fill(name); await h.field(page,'File contents').fill(content); await h.field(page,'Commit message').fill(message); await h.button(page,'Commit changes').click(); await expect(h.text(page,content)).toBeVisible(); await h.link(page,'Commits').click(); await expect(h.link(page,message)).toBeVisible();",newfile+"await h.field(page,'File name').fill('../invalid.md'); await h.field(page,'File contents').fill('must not be saved'); await h.field(page,'Commit message').fill(''); await h.button(page,'Commit changes').click(); await expect(h.fileValidationReason(page).first()).toBeVisible();")
    add('REQ-5-1-1',*[repo+f"await h.link(page,'Issues').click(); await h.filterStatus(page,{json.dumps(status)}); await page.getByRole('searchbox',{{name:'Search issues',exact:true}}).fill({json.dumps(title)}); await expect(h.link(page,{json.dumps(title)})).toBeVisible();" for status,title in [('Open','Improve onboarding'),('Closed','Legacy welcome text')]])
    detail=issue('Improve onboarding')+"await expect(h.text(page,'Describe the onboarding improvement.')).toBeVisible(); await expect(h.text(page,'Open').first()).toBeVisible(); await expect(page.getByRole('article').first()).toBeVisible(); "
    add('REQ-5-1-2',detail,detail+"await page.reload(); await expect(page.getByRole('heading',{name:'Improve onboarding',exact:true})).toBeVisible();",detail+issue('Improve onboarding')+"await expect(h.text(page,'Describe the onboarding improvement.')).toBeVisible();")
    newissue=login('issue-author')+repo+"await h.link(page,'Issues').click(); await h.link(page,'New issue').click(); "
    add('REQ-5-2-1',newissue+"const title=h.unique('pw-issue'),body=h.unique('issue-body'); await h.field(page,'Title').fill(title); await h.field(page,'Description').fill(body); await h.button(page,'Submit new issue').click(); await h.persisted(page,async()=>{await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible(); await expect(h.text(page,body).first()).toBeVisible();});",newissue+"await h.field(page,'Title').fill('   '); await h.button(page,'Submit new issue').click(); await expect(h.titleRequiredReason(page).first()).toBeVisible(); await expect(h.field(page,'Title')).toHaveValue('   ');")
    add('REQ-5-2-2',login('issue-editor')+issue('Editable onboarding issue')+"const title=h.unique('updated-title'),body=h.unique('updated-body'); await h.button(page,'Edit issue title').click(); await h.field(page,'Issue title').fill(title); await h.button(page,'Save issue title').click(); await h.button(page,'Edit issue description').click(); await h.field(page,'Issue description').fill(body); await h.button(page,'Save issue description').click(); await h.persisted(page,async()=>{await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible(); await expect(h.text(page,body).first()).toBeVisible();});",login('issue-editor')+issue('Original issue title')+"await h.button(page,'Edit issue title').click(); await h.field(page,'Issue title').fill('   '); await h.button(page,'Save issue title').click(); await expect(h.titleRequiredReason(page).first()).toBeVisible(); await page.reload(); await expect(page.getByRole('heading',{name:'Original issue title',exact:true})).toBeVisible();")
    add('REQ-5-2-3',login('issue-commenter')+issue('Commentable onboarding issue')+"const body=h.unique('pw-comment'); await h.field(page,'Comment').fill(body); await h.button(page,'Comment').click(); await h.persisted(page,()=>expect(h.text(page,body).first()).toBeVisible());",login('issue-commenter')+issue('Comment validation issue')+"const before=await page.getByRole('article').allTextContents(); await h.field(page,'Comment').fill('   '); if(await h.button(page,'Comment').isEnabled()) await h.attemptSubmission(page,h.button(page,'Comment')); await page.reload(); await expect.poll(()=>page.getByRole('article').allTextContents()).toEqual(before);")
    for node,title,control,value,searchlabel,remove in [('REQ-5-3-1','Assignable onboarding issue','Assignees','bob-reviewer','Search assignees','bob-reviewer'),('REQ-5-3-2','Labelable onboarding issue','Labels','bug',None,'bug'),('REQ-5-3-3','Milestone onboarding issue','Milestone','v1.0',None,'None')]:
        add(node,login('issue-editor')+issue(title)+f"await h.button(page,{json.dumps(control)}).click(); "+(f"await h.field(page,{json.dumps(searchlabel)}).fill({json.dumps(value)}); " if searchlabel else '')+f"await h.option(page,{json.dumps(value)}); await h.persisted(page,()=>expect(h.metadataValue(page,{json.dumps(control)},{json.dumps(value)}).first()).toBeVisible()); await h.button(page,{json.dumps(control)}).click(); await h.option(page,{json.dumps(remove)}); await h.persisted(page,()=>expect(h.metadataValue(page,{json.dumps(control)},{json.dumps(value)})).toHaveCount(0));")
    add('REQ-5-4',login('issue-editor')+issue('Closable onboarding issue')+"await h.button(page,'Close issue').click(); await expect(h.text(page,'Closed').first()).toBeVisible(); await h.button(page,'Reopen issue').click(); await h.persisted(page,()=>expect(h.button(page,'Close issue')).toBeVisible());",login('issue-viewer')+issue('Protected onboarding issue')+"await expect(h.button(page,'Close issue')).toHaveCount(0); await expect(h.button(page,'Reopen issue')).toHaveCount(0);")
    add('REQ-6-1',login('protection-admin')+"await h.repo(page,'branch-protection-demo'); await h.settings(page,'Branches'); await h.button(page,'Add branch protection rule').click(); await h.field(page,'Branch name pattern').fill('main'); await page.getByRole('checkbox',{name:'Require 1 approval',exact:true}).check(); await page.getByRole('checkbox',{name:'Require status check test',exact:true}).check(); await h.action(page,['Create','Save changes']).click(); await h.persisted(page,async()=>{await expect(h.visibleText(page,'main').first()).toBeVisible(); await expect(h.visibleText(page,'1 approval').first()).toBeVisible(); await expect(h.visibleText(page,'Require status check test').first()).toBeVisible();});",login('protection-viewer')+"await h.repo(page,'branch-protection-demo'); await h.settings(page,'Branches'); await expect(h.button(page,'Add branch protection rule')).toHaveCount(0);",login('protection-admin')+pr('Protection status onboarding PR','branch-protection-demo')+"await expect(h.text(page,'test: pending')).toBeVisible(); await h.choose(page,'test','success'); await h.action(page,['Save','Update']).click(); await h.persisted(page,async()=>{await expect(h.text(page,'test: success')).toBeVisible(); await expect(h.containsValue(page,'protection-admin').first()).toBeVisible();});")
    prlist=repo+"await h.link(page,'Pull requests').click(); await h.filterStatus(page,'Open'); "
    add('REQ-6-2-1',prlist+"await h.link(page,'Improve onboarding').click(); await expect(page.getByRole('heading',{name:'Improve onboarding',exact:true})).toBeVisible();",prlist+"await h.persisted(page,()=>expect(h.link(page,'Improve onboarding')).toBeVisible());",prlist+prlist+"await expect(h.link(page,'Improve onboarding')).toBeVisible();")
    comparison=login('pr-contributor')+repo+"await h.link(page,'Pull requests').click(); await h.link(page,'New pull request').click(); await h.choose(page,'Base','main'); "
    add('REQ-6-2-2',comparison+"await h.choose(page,'Compare','feature-search'); await h.button(page,'Compare changes').click(); await expect(h.text(page,'src/search.ts')).toBeVisible(); await expect(h.comparisonCommitInformation(page,'Implement search flow',1).first()).toBeVisible();",comparison+"await h.choose(page,'Compare','main'); await h.button(page,'Compare changes').click(); await expect(h.noDifferences(page).first()).toBeVisible(); await expect(h.button(page,'Create pull request')).toBeDisabled();")
    createpr=login('pr-contributor')+repo+"await h.link(page,'Compare').click(); await expect(h.text(page,'src/search.ts')).toBeVisible(); "
    add('REQ-6-2-3',createpr+"await h.button(page,'Create pull request').click(); const title=h.unique('pw-pr'); await h.field(page,'Title').fill(title); await h.button(page,'Create pull request').click(); await h.persisted(page,async()=>{await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible(); await expect(h.text(page,'Open').first()).toBeVisible();});",createpr+"await h.button(page,'Create pull request').click(); await h.field(page,'Title').fill('   '); await h.button(page,'Create pull request').click(); await expect(h.titleRequiredReason(page).first()).toBeVisible(); await expect(h.field(page,'Title')).toHaveValue('   ');")
    add('REQ-6-2-4',createpr+"await h.choose(page,'Compare','draft-create-feature'); await h.button(page,'Compare changes').click(); "+"await h.button(page,'Create draft pull request').click(); const title=h.unique('pw-draft'); await h.field(page,'Title').fill(title); await h.button(page,'Create draft pull request').click(); await h.persisted(page,async()=>{await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible(); await expect(h.text(page,'Draft').first()).toBeVisible(); await expect(h.button(page,'Merge pull request')).toBeDisabled();});",login('draft-author')+pr('Draft onboarding update')+"await h.button(page,'Ready for review').click(); const confirm=h.button(page,'Confirm'); if(await confirm.isVisible()) await confirm.click(); await h.persisted(page,async()=>{await expect(page.getByRole('heading',{name:'Draft onboarding update',exact:true})).toBeVisible(); await expect(h.text(page,'Open').first()).toBeVisible(); await expect(h.text(page,'draft-feature').first()).toBeVisible();});")
    overview=pr('Overview onboarding PR')
    add('REQ-6-3-1',overview+"await h.link(page,'Commits').click(); await expect(h.renderedSubstring(page,'Implement search flow').first()).toBeVisible(); await h.link(page,'Files changed').click(); await expect(h.text(page,'src/search.ts')).toBeVisible();",overview+"await page.reload(); await expect(page.getByRole('heading',{name:'Overview onboarding PR',exact:true})).toBeVisible(); await h.link(page,'Commits').click(); await expect(h.renderedSubstring(page,'Implement search flow').first()).toBeVisible();",overview+overview+"await h.link(page,'Files changed').click(); await expect(page.getByRole('heading',{name:'Overview onboarding PR',exact:true})).toBeVisible(); await expect(h.text(page,'src/search.ts')).toBeVisible();")
    add('REQ-6-3-2',pr('Public onboarding PR')+"await h.link(page,'Files changed').click(); await expect(h.text(page,'src/search.ts')).toBeVisible(); await expect(page.getByText(/\\d+ additions/)).toBeVisible(); await expect(page.getByText(/\\d+ deletions/)).toBeVisible();")
    comment="await h.link(page,'Files changed').click(); await h.button(page,'Add comment').first().click(); const body=h.unique('pw-review'); await h.field(page,'Comment').fill(body); "
    add('REQ-6-3-3',login('pr-reviewer')+pr('Reviewable onboarding PR')+comment+"await h.button(page,'Add single comment').click(); await h.persisted(page,()=>expect(h.text(page,body).first()).toBeVisible());",login('pr-reviewer')+pr('Pending review onboarding PR')+comment+"await h.button(page,'Start a review').click(); await h.persisted(page,async()=>{await expect(h.text(page,body).first()).toBeVisible(); await expect(page.getByText(/Pending review/).first()).toBeVisible();});")
    review="await h.link(page,'Files changed').click(); await h.button(page,'Review changes').click(); "
    add('REQ-6-3-4',login('pr-reviewer')+pr('Reviewable onboarding PR')+review+"await page.getByRole('radio',{name:'Approve',exact:true}).check(); await h.button(page,'Submit review').click(); await expect(h.text(page,'Approved').first()).toBeVisible();",login('pr-reviewer')+pr('Change request onboarding PR')+review+"const summary=h.unique('pw-summary'); await (await h.reviewSummary(page)).fill(summary); await page.getByRole('radio',{name:'Request changes',exact:true}).check(); await h.button(page,'Submit review').click(); await h.persisted(page,async()=>{await expect(h.text(page,'Changes requested').first()).toBeVisible(); await expect(h.text(page,summary)).toBeVisible();});")
    add('REQ-6-4',login('pr-author')+pr('Reviewer request onboarding PR')+"await h.button(page,'Reviewers').click(); await h.field(page,'Search').fill('bob-reviewer'); await h.option(page,'bob-reviewer'); await h.persisted(page,()=>expect(h.button(page,'Remove bob-reviewer')).toBeVisible()); await h.button(page,'Remove bob-reviewer').click(); await h.persisted(page,()=>expect(h.button(page,'Remove bob-reviewer')).toHaveCount(0));")
    add('REQ-6-5',login('pr-maintainer')+pr('Mergeable onboarding PR','merge-onboarding-demo')+"await expect(page.getByText('Create a merge commit',{exact:true}).first()).toBeVisible(); await expect(h.button(page,'Merge pull request')).toBeEnabled(); await h.button(page,'Merge pull request').click(); await h.button(page,'Confirm merge').click(); await h.persisted(page,()=>expect(h.text(page,'Merged').first()).toBeVisible()); await expect(h.containsValue(page,'pr-maintainer').first()).toBeVisible(); await h.repo(page,'merge-onboarding-demo'); await h.link(page,'src').click(); await h.link(page,'search.ts').click(); await expect(h.text(page,'export const search = \"merged search flow\";')).toBeVisible();",login('pr-maintainer')+pr('Blocked onboarding PR','merge-onboarding-demo')+"await h.persisted(page,()=>expect(h.button(page,'Merge pull request')).toBeDisabled()); await expect(page.getByText(/Review required|protection/).first()).toBeVisible(); await expect(h.text(page,'Open').first()).toBeVisible();")
    add('REQ-6-6',login('pr-author')+pr('Closable onboarding PR')+"await h.button(page,'Close pull request').click(); await expect(h.text(page,'Closed').first()).toBeVisible(); await h.button(page,'Reopen pull request').click(); await h.persisted(page,()=>expect(h.button(page,'Close pull request')).toBeVisible());",login('pr-viewer')+pr('Protected onboarding PR')+"await expect(h.button(page,'Close pull request')).toHaveCount(0); await expect(h.button(page,'Reopen pull request')).toHaveCount(0);")

    requirements=yaml.safe_load((Path(__file__).parent/'tasks/hackathon--github/requirements.yaml').read_text())
    def leaves(node):
        if not node.get('children'): yield node
        for child in node.get('children',[]): yield from leaves(child)
    nodes=list(leaves(requirements))
    assert set(bodies)=={n['id'] for n in nodes}
    assert sum(map(len,bodies.values()))==100
    for node in nodes:
        assert len(bodies[node['id']])==len(node['scenarios']),node['id']
        for i,body in enumerate(bodies[node['id']],1):g(node['id'],f'requirement scenario {i}',body)

def suite_cases(g):
    register(g)
    from embedded_github_contract_gap_cases import register as register_contract_gaps
    register_contract_gaps(g)
    from embedded_github_stage1_gap_cases import register as register_stage1_gaps
    register_stage1_gaps(g)
    from embedded_github_selftest_cases import register as register_selftest
    register_selftest(g)
    from embedded_github_navigation_readiness_cases import register as register_navigation_readiness
    register_navigation_readiness(g)
    from embedded_github_selftest_44831560_cases import register as register_selftest_44831560
    register_selftest_44831560(g)
    regressions=json.loads((Path(__file__).parent/'github_regression_recipes.json').read_text())
    for file,recipes in regressions.items():
        for row in recipes:
            created=g(row['node_id'],row['title'],row['body'],fixture=row.get('fixture'),file=file,requires=row['requires'])
            for key,value in row.items():
                if key not in {'body','title','file','setup_requires'}:
                    created[key]=value
