"""Reviewed GitHub shared business model; no mandated routes or storage format."""

def design():
    entities = {
        'account': {'id':'stable account ID','username':'globally unique 1–39 lowercase ASCII username','email':'unique verified email','password':'validated credential, never echoed','available':'boolean'},
        'session': {'id':'unique session ID distinct from account ID','account_id':'account reference','active':'boolean; only the current browser session is ended by sign-out'},
        'organization': {'id':'stable organization ID','identifier':'globally unique 1–39 lowercase ASCII characters','display_name':'trimmed 1–100 characters','owners':'account IDs','members':'account IDs'},
        'team': {'id':'stable team ID','organization_id':'owning organization reference','name':'organization-scoped team name','description':'optional','parent_id':'optional team in same organization; acyclic','direct_members':'current organization-member account IDs'},
        'repository': {'id':'stable repository ID','owner_id':'account or organization ID','name':'owner-scoped name','visibility':'Public|Private','default_branch':'existing branch reference','source_repository_id':'optional fork source identity'},
        'repository_grant': {'repository_id':'repository reference','subject_type':'account|team','subject_id':'stable subject ID','role':'Read|Triage|Write|Maintain|Admin','grantor':'account reference','time':'grant/change timestamp'},
        'commit': {'id':'immutable commit identifier','repository_id':'repository reference','parents':'commit references; merge has two parents','files':'complete branch file snapshot','author':'account ID','message':'trimmed 1–72 characters for web commits','time':'commit timestamp'},
        'branch': {'repository_id':'repository reference','name':'repository-scoped valid branch name','head':'current commit ID'},
        'issue': {'id':'stable issue ID','repository_id':'repository reference','number':'unique repository-scoped issue number','title':'trimmed 1–256 characters','description':'up to 65536 characters','author':'account ID','status':'Open|Closed','assignees':'eligible account IDs','labels':'current-repository label IDs','milestone':'optional current-repository milestone ID'},
        'pull_request': {'id':'stable PR ID','repository_id':'repository reference','number':'unique repository-scoped PR number','title':'non-empty title','description':'optional description','author':'account ID','base':'target branch','compare':'source branch','base_commit':'base snapshot ID','compare_commit':'current compare snapshot ID','status':'Draft|Open|Closed|Merged','merge_commit':'optional actual resulting commit ID'},
        'discussion': {'id':'stable comment/activity ID','work_item':'scoped issue or PR reference','author':'account ID','body':'complete saved text','kind':'description|comment|review summary|status activity','time':'event timestamp'},
        'review': {'id':'immutable review ID','pr_id':'PR reference','reviewer':'non-author Write/Maintain/Admin account ID','compare_commit':'reviewed compare commit ID','decision':'Approve|Request changes','summary':'optional explanation','time':'review timestamp'},
        'inline_comment': {'id':'stable comment ID','pr_id':'PR reference','file_path':'changed file path','compare_commit':'anchored compare commit','line':'specific added/deleted line position','author':'account ID','body':'complete saved text','publication':'Pending|Published','outdated':'true when published anchor is no longer current'},
        'reviewer_request': {'pr_id':'PR reference','reviewer':'eligible non-author account ID','operator':'requesting/removing account ID','time':'relationship change timestamp'},
        'branch_protection': {'repository_id':'repository reference','branch_name':'exact existing branch name; no wildcard semantics','require_1_approval':'independent boolean','require_test_success':'independent boolean'},
        'check': {'pr_id':'PR reference','compare_commit':'current compare commit ID','name':'test','status':'pending|success|failure','setter':'repository Admin account ID','time':'setter timestamp'},
    }
    groups = [
        ('account', ['REQ-1-1-1','REQ-1-1-2','REQ-1-1-3','REQ-1-3'], 'Registration, recovery and password-change commands', 'Sign-in credential checks and account settings', 'Global account ID; usernames/emails identify an account and are never session IDs'),
        ('session', ['REQ-1-1-2','REQ-1-2'], 'Sign-in and current-browser sign-out', 'Every protected read and mutation', 'A unique session ID refers to exactly one account and has its own active state'),
        ('organization', ['REQ-2-1-1','REQ-2-1-2','REQ-2-2-3','REQ-2-2-4'], 'Create organization and add/remove member', 'Organization listing, team membership and repository authorization', 'Organization ID scopes all ownership and member relationships'),
        ('team', ['REQ-2-2-1','REQ-2-2-2','REQ-2-3'], 'Owner team creation/member/hierarchy commands', 'Team tree, direct member lists and repository grant evaluation', 'Team ID is organization-scoped; hierarchy creates no implicit membership or grant'),
        ('repository', ['REQ-3-1','REQ-3-2-1','REQ-3-2-2','REQ-3-2-3','REQ-3-3','REQ-3-4'], 'Repository create/fork and visibility commands', 'Search, organization listing, overview, clone and all scoped work items', 'Stable repository ID plus owner-scoped name; all private reads use the same access policy'),
        ('repository_grant', ['REQ-2-3','REQ-3'], 'Owner/Admin direct grant replacement and membership revocation', 'Every repository role check', 'One role per (repository, subject); effective role is the highest still-valid direct/team/Owner grant'),
        ('commit', ['REQ-4-1','REQ-4-2-1','REQ-4-2-2','REQ-4-2-3','REQ-4-4','REQ-6-5'], 'Web file commit and atomic merge', 'File views, scoped search, history, comparison and PR diffs', 'Immutable repository-scoped commit IDs with parent references and complete file snapshots'),
        ('branch', ['REQ-4-3-1','REQ-4-3-2','REQ-4-3-3','REQ-4-4','REQ-6-2-2','REQ-6-5'], 'Branch creation, default selection, file commit and merge', 'Code page branch selection and compare/diff computation', '(repository ID, branch name) refers to a head; current-page branch is not an invented user preference'),
        ('issue', ['REQ-5-1-1','REQ-5-1-2','REQ-5-2-1','REQ-5-2-2','REQ-5-3-1','REQ-5-3-2','REQ-5-3-3','REQ-5-4'], 'Issue create/edit/metadata/status commands', 'Issue list/detail and discussion', 'Unique issue number within its repository, stable identity through edits and status changes'),
        ('pull_request', ['REQ-6-2-1','REQ-6-2-2','REQ-6-2-3','REQ-6-2-4','REQ-6-3-1','REQ-6-3-2','REQ-6-5','REQ-6-6'], 'PR create/ready/close/reopen and merge', 'PR list/detail, comparison, commits, diff and merge eligibility', 'Unique repository-scoped PR number; base is target and compare is source; Merged is terminal'),
        ('discussion', ['REQ-5-2-3','REQ-5-1-2','REQ-6-3-1','REQ-6-3-4','REQ-6-6'], 'Comment, review and status-event commands', 'Conversation and activity views', 'Work-item-scoped historical records; removing metadata/reviewer requests must not erase history'),
        ('review', ['REQ-6-3-4','REQ-6-1','REQ-6-5'], 'Non-author current-commit review submission', 'Review timeline and merge eligibility', 'Each reviewer latest decision on current compare commit is effective; old history persists'),
        ('inline_comment', ['REQ-6-3-3','REQ-6-3-4'], 'Single comment, pending draft and review submission', 'Author draft view and published diff comments', 'File path + compare commit + changed line anchor; pending comments remain private'),
        ('reviewer_request', ['REQ-6-4'], 'Author/Maintain/Admin/Owner request/remove reviewer', 'Reviewer area; separate from effective submitted reviews', '(PR ID, eligible reviewer ID) relationship; removal changes no submitted decision'),
        ('branch_protection', ['REQ-6-1','REQ-4-4','REQ-6-5'], 'Repository Admin protection rule command', 'Current-state merge eligibility', '(repository ID, exact branch name); approval/check requirements are independent'),
        ('check', ['REQ-6-1','REQ-6-5'], 'Repository Admin current-compare-commit check update', 'Checks area and required-test merge condition', '(PR ID, current compare commit, test); stale status cannot satisfy a different commit'),
    ]
    domain = [{'entity':name,'requirements':reqs,'identity':identity,
               'storage':'One authoritative aggregate or transactional store shared by all producers and consumers; physical schema and module paths remain implementation-defined',
               'producers':[writer],'consumers':[reader]} for name,reqs,writer,reader,identity in groups]
    contracts = [
        {'requirements':['REQ-5','REQ-6','REQ-2-3'], 'invariants':['Use the operation-specific role matrices in REQ-5 and REQ-6. Write does not automatically gain Triage operations; Maintain/Admin and organization Owner receive their explicitly stated capabilities.', 'Private reads require Owner, a valid direct grant, or direct membership in a granted team. Ordinary organization membership and team ancestry grant no private access.', 'A direct grant replacement stores one record. Revocation removes associated membership/team/grant access without deleting the account.']},
        {'requirements':['REQ-1-1-1','REQ-1-1-2','REQ-1-1-3','REQ-1-2','REQ-1-3'], 'invariants':['Registration marks email verified and returns to sign-in. Keep attempted non-sensitive values on rejection and do not echo credentials.', 'Unknown, wrong-password and unavailable-account sign-in use the same Invalid credentials response and create no session.', 'Recovery is the fixed local demonstration code 123456, displayed to both known and unknown emails; change credentials only for the associated registered account with valid input.', 'Sign-out confirmation invalidates only the current browser session. Cancel retains the current page/session. Refresh/back/direct protected entry must re-evaluate active authentication.']},
        {'requirements':['REQ-4-1','REQ-4-2-1','REQ-4-2-2','REQ-4-2-3','REQ-4-3-1','REQ-4-3-2','REQ-4-3-3','REQ-4-4'], 'invariants':['File content, branch head, commit history and diff share immutable snapshots. Commit path/content/message/author/parent/target branch as one operation.', 'Read-only browse/search/compare operations create no branch or commit. A branch selector updates the same current-page branch and file snapshot.', 'Default-branch change points to an existing branch and retains the previous branch.']},
        {'requirements':['REQ-5-2-1','REQ-5-2-2','REQ-5-2-3','REQ-5-3-1','REQ-5-3-2','REQ-5-3-3','REQ-5-4'], 'invariants':['Separate title and description save commands. Rejected empty/overlong input leaves the original persisted property unchanged.', 'Metadata pickers save immediately and close on selection; assignee/label toggle removes only the relationship, and None removes only the milestone association.', 'Assignable accounts and labels/milestones are validated in the current repository. Historical activity does not count as current metadata.', 'Close/reopen changes only issue status and activity, preserving title/body/comments/metadata.']},
        {'requirements':['REQ-6-1','REQ-6-2-2','REQ-6-2-3','REQ-6-2-4','REQ-6-3-3','REQ-6-3-4','REQ-6-4','REQ-6-5','REQ-6-6'], 'invariants':['Compute comparisons from current base/compare commit snapshots; same/no-difference comparison cannot create a PR.', 'Draft cannot be reviewed or merged. Ready for review changes the same PR to Open without changing identity, branches, commits or title.', 'Current compare commit invalidates prior review decisions/checks when it changes. Only latest current-commit non-author reviewer decisions affect eligibility; any valid Request changes blocks merging.', 'At confirmation re-read both heads, conflicts, protection toggles, reviews and current check. Commit merge parents, base head, PR Merged status and merger metadata atomically. Rejection leaves both branch and PR unchanged.', 'Unprotected branches still reject conflicts and current Request changes; configured approval/test conditions are independently enforced on protected targets.', 'Close/reopen never updates branch heads. Merged is terminal. Reviewer request removal never removes existing reviews or comments.']},
    ]
    return {'data_model':entities,'routes':[],'pages':[],'modules':[], 'domain_contracts':domain,
            'contracts':contracts,'commands':[],
            'notes':'Source-reviewed shared business contracts, not an official implementation schema or measured product pass. Raw requirements are authoritative. URL paths, database format and source module names are implementation choices; implement public ARIA controls exactly where requirements prescribe them. Provision fixtures only for a new store or explicit migration, preserve user edits/deletions on restart, and use one authoritative policy/transaction for related effects.'}
